import { Box } from "@chakra-ui/react";
import Head from "next/head";
import HeroBg from "../assets/bg-hero.svg";
import Image from "next/image";
import Hero from "../components/Hero";
import Why from "../components/Why";
import About from "../components/About";

export default function Home() {
	return (
		<div>
			<Head>
				<title>MuskTweetFloki</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<svg
				width="1920"
				height="165"
				viewBox="0 0 1920 165"
				fill="none"
				xmlns="http://www.w3.org/2000/svg"
			>
				<path
					d="M1920 0H0V107C0 107 430 236 960 107C1490 -22 1920 107 1920 107V0Z"
					fill="#faae60"
				/>
			</svg>

			<Why />
			<About />
		</div>
	);
}
