import Head from "next/head";
import Hero from "../components/Hero";
import Why from "../components/Why";
import About from "../components/About";
import Roadmap from "../components/Roadmap";
import Proof from "../components/Proof";
import HowToBuy from "../components/HowToBuy";
import Footer from "../components/Footer";
import { Square, Button } from "@chakra-ui/react";
import { IoChevronUp } from "react-icons/io5";

export default function Home() {
	const scrollTop = () => {
		window.scrollTo({ top: 0, behavior: "smooth" });
	};

	return (
		<>
			<Head>
				<title>MuskTweetFloki</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<Why />
			<About />
			<Roadmap />
			<Proof />
			<HowToBuy />
			<Footer />

			<Square
				pos="fixed"
				bottom={5}
				right={5}
				onClick={scrollTop}
				opacity="0.8"
			>
				<Button
					p={{ base: "5", md: "7" }}
					fontSize={{ base: "2xl", md: "4xl" }}
					shadow="md"
					_focus={{ outline: "none" }}
					color="#f56713"
				>
					<IoChevronUp />
				</Button>
			</Square>
		</>
	);
}
